home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_config, name='main'),
    path('detail/<int:user_id>', views.detail, name='detail'),
    path('add/', views.add, name='add_note'),
    path('edit/<int:user_id>', views.edit, name='edit_note'),
    path('search/', views.search, name='search'),
    path('delete/<int:user_id>', views.delete, name='delete')
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls'))
]

home/models.py
from django.db import models
from extensions.utils import jalali_converter
from django.contrib.auth.models import User


class Note(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)

    def jcreated(self):
        return jalali_converter(self.created)

    def __str__(self):
        return self.title

home/forms.py
from django import forms
from .models import Note


class AddNoteFrom(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title','body')
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control', 'placeholder': 'تایتل'
            }),
            'body': forms.Textarea(attrs={
                'class': 'form-control', 'placeholder': 'متن'
            })
        }

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Note
from .forms import AddNoteFrom
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def home_config(request):
    if request.user.is_authenticated:
        notes = Note.objects.filter(user=request.user).order_by('-created')
        paginator = Paginator(notes, 3)
        page_number = request.GET.get('page')
        objects_list = paginator.get_page(page_number)
        return render(request, 'home/home.html', {'notes': objects_list, 'do': 'افزودن'})
    else:
        return redirect('account:login')


def detail(request, user_id):
    if request.user.is_authenticated:
        # todo = Note.objects.get(id=id,user=request.user)
        note = get_object_or_404(Note,id=user_id, user=request.user)
        return render(request, 'home/details.html', {'note': note})
    else:
        return redirect('account:login')


def add(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = AddNoteFrom(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                Note.objects.create(title=cd['title'], body=cd['body'],user=request.user)
                messages.success(request, 'یادداشت با موفقیت ثبت شد', extra_tags='success')
                return redirect("home:main")
        else:
            form = AddNoteFrom()
        return render(request, 'home/addnote.html', {'form': form, 'do': 'افزودن'})
    else:
        return redirect('account:login')


def edit(request, user_id):
    if request.user.is_authenticated:
        # note = Note.objects.get(id=user_id)
        note = get_object_or_404(Note, id=user_id, user=request.user)
        if request.method == 'POST':
            form = AddNoteFrom(instance=note, data=request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'یادداشت با موفقیت ویرایش شد', extra_tags='success')
                return redirect("home:main")
        else:
            form = AddNoteFrom(instance=note)
        return render(request, 'home/addnote.html', {'form': form, 'do': 'ویرایش'})
    else:
        return redirect('account:login')


def search(request):
    if request.user.is_authenticated:
        q = request.GET.get('q')
        notes = Note.objects.filter(title__icontains=q, user=request.user).order_by('-created')
        page_number = request.GET.get('page')
        paginator = Paginator(notes, 3)
        objects_list = paginator.get_page(page_number)
        return render(request, 'home/home.html', {'notes': objects_list, 'q': q, 'do': 'افزودن'})
    else:
        return redirect('account:login')


def delete(request, user_id):
    if request.user.is_authenticated:
        note = Note.objects.get(id=user_id,user=request.user)
        note.delete()
        messages.success(request, 'یادداشت با موفقیت حذف شد', extra_tags='success')
        return redirect('home:main')
    else:
        return redirect('account:login')

home/templates/home/addnote.html
{% extends 'base.html' %}
{% load static %}


{% block style %}{% static 'style/home.css' %}{% endblock %}
{% block title %}add note{% endblock %}

{% block content %}
        <section class="bg-beige">
             <div class="container">
            <div class="row my-content">
                <div class="card bg-black p-5">
            <form action="" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.title }}
                </div>
                <div class="mb-3">
                    {{ form.body }}
                </div>
                <div>
                    <button type="submit" class="btn btn-outline-light">{{ do }}</button>
                </div>
            </form>
        </div>
            </div>
        </div>
        </section>

{% endblock %}

home/templates/home/details.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'style/home.css' %}{% endblock %}
{% block title %}detail{% endblock %}

{% block content %}
    <div class="container">
        <div class="row my-content">
            <div class="card bg-black mb-3 my-card" style="max-width: 18rem;">
                <div class="card-body text-success">
                    <ul class="list-group list-group-flush">
                        <li class="my_li_detail ms-2">
                            <p class="fw-bold">{{ note.title }}</p>
                            <hr>
                            <p class="fw-bold">{{ note.body }}</p>
                        </li>
                    </ul>
                </div>
                <div class="d-flex justify-content-between">
                    <button type="button" class="btn btn-danger mb-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        حذف
                    </button>

                    <a href="{% url 'home:edit_note' note.id %}" class="btn btn-success mb-2">ویرایش</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">حذف یادداشت {{ todo.title }}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    آیا از حذف این یادداشت مطمئن هستید؟
                </div>
                <div class="modal-footer">
                    <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">خیر
                    </a>
                    <a href="{% url 'home:delete' note.id %}" type="button" class="btn btn-primary">بله</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}


{% block style %}{% static 'style/home.css' %}{% endblock %}

{% block title %}home{% endblock %}

{% block content %}


    <div class="container">
        <div class="row justify-content-center my-content">
            <div class="card bg-black mb-3 my-card">
                <div class="card-header text-center">یادداشت ها</div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for note in notes %}
                            <a href="{% url 'home:detail' note.id %}" class="list-group-item bg-black my_li ms-2">
                                    <p class="bold">{{ note.title }}</p>
                                    <p>{{ note.body|truncatewords:3 }}</p>
                                    <p class="date-style">{{ note.jcreated }}</p>
                            </a>
                        {% endfor %}
                    </ul>
                </div>
                <div class="d-flex align-items-center justify-content-between mt-5">
                    {% if notes.has_other_pages %}
                        <nav class=" d-flex justify-content-end mt-3" aria-label="Page navigation example">
                            <ul class="pagination">
                                {% if notes.has_previous %}
                                    <li class="page-item"><a class="page-link" href="?page={{ notes.previous_page_number }}{% if request.Get.q %}&q={{ request.GET.q }}{% else %}&q={{ q }}{% endif %}">Previous</a>
                                    </li>
                                {% endif %}
                                {% for page in notes.paginator.page_range %}
                                    {% if notes.number == page %}
                                        <li class="page-item active"><a class="page-link" href="?page={{ page }}{% if request.Get.q %}&q={{ request.GET.q }}{% else %}&q={{ q }}{% endif %}">{{ page }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ page }}{% if request.Get.q %}&q={{ request.GET.q }}{% else %}&q={{ q }}{% endif %}">{{ page }}</a>
                                        </li>
                                    {% endif %}

                                {% endfor %}
                                {% if notes.has_next %}
                                    <li class="page-item"><a class="page-link" href="?page={{ notes.next_page_number }}{% if request.Get.q %}&q={{ request.GET.q }}{% else %}&q={{ q }}{% endif %}">Next</a>
                                {% endif %}
                                </li>
                            </ul>
                        </nav>
                    {% endif %}
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'home:add_note' %}" class="btn btn-outline-light">{{ do }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>




{% endblock %}