account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('register/',views.user_register,name='register'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/<int:user_id>',views.user_profile,name='profile'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_config, name='main'),
    path('detail/<int:user_id>', views.detail, name='detail'),
    path('add/', views.add, name='add_note'),
    path('edit/<int:user_id>', views.edit, name='edit_note'),
    path('search/', views.search, name='search'),
    path('delete/<int:user_id>', views.delete, name='delete')
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls'))
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
            {{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/inc/nav.html
<nav class="bg-black">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                {% if request.user.is_authenticated %}
                    <ul class="col-2 navbar list-unstyled">
                        <li class="nav-item"><a class="my-nav-link text-light" href="{% url 'home:main' %}">خانه</a></li>
                        <li class="nav-item"><a class="my-nav-link text-light" href="{% url 'home:add_note' %}">افزودن</a></li>
                    </ul>
                    <div class="col-4">
                        <form class="form-inline my-2 my-lg-0 d-flex justify-content-between" action="{% url 'home:search' %}" method="GET">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q">
                            <button type="submit" class="btn btn-outline-light my-2 my-sm-0" type="submit">جستجو</button>
                        </form>
                    </div>
                    <div class="col-2">
                        <div class="text-end">
                            <a href="{% url 'account:profile' request.user.id %}" class="my-nav-link text-light me-2 ">سلام {{ request.user }}</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'account:logout' %}">خروج</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>